include:
  - ../mongodb/docker-compose.yaml
  - ../kafka/docker-compose.yaml

services:
  nest:
    build: .
    volumes:
      - .:/home/root/app
    container_name: nest
    ports:
      - 3000:3000